language: node_js
node_js: lts/*

branches:
  only:
    - master
    - develop

install:
  - npm i -f
  - npm i rollup node-sass svelte-preprocess rollup-plugin-postcss --save-dev

cache:
  directories:
  - "./node_modules"
  - "$HOME/.npm"

jobs:
  include:
    - stage: release
      script: bash docs.sh
